/* Configuración centralizada: actualice estos datos sin modificar el resto de la página. */
const CONFIG={empresa:'NAVISUA J&J E.I.R.L.',telefono:'947185874',correo:'navisua.eirl@gmail.com',precios:[['Papel','kg','Consultar'],['Cartón','kg','Consultar'],['PET','kg','Consultar'],['Plásticos','kg','Consultar'],['Film','kg','Consultar'],['Metales','kg','Consultar'],['Otros','kg','Consultar']],servicios:[['♻️','Recolección de residuos','Recojo programado y responsable para su operación.'],['🚛','Transporte de residuos sólidos','Traslado seguro con unidades operativas.'],['▤','Gestión de papel','Aprovechamiento y manejo de papel recuperable.'],['▣','Gestión de cartón','Segregación y valorización de cartón.'],['♳','Gestión de plásticos','Soluciones para plásticos y materiales recuperables.'],['⚙','Gestión de metales','Manejo de metales para valorización.'],['🌱','Materiales reciclables','Clasificación de materiales con potencial de recuperación.'],['↻','Valorización','Convertimos residuos en oportunidades de valor.'],['🏭','Servicios industriales','Atención para empresas e industrias.']],noticias:[['MINAM','Gestión integral de residuos sólidos','Información y recursos ambientales para la gestión responsable de residuos.','https://www.gob.pe/minam'],['OEFA','Fiscalización ambiental','Conozca las acciones y herramientas de fiscalización ambiental en Perú.','https://www.gob.pe/oefa'],['SINIA','Información ambiental','Acceda a datos y contenidos sobre ambiente, reciclaje y economía circular.','https://sinia.minam.gob.pe/']]};
const message=`Hola ${CONFIG.empresa}, deseo información sobre sus servicios de gestión de residuos sólidos.`;
document.querySelectorAll('[data-wa]').forEach(link=>link.href=`https://wa.me/51${CONFIG.telefono}?text=${encodeURIComponent(message)}`);
document.getElementById('serviceGrid').innerHTML=CONFIG.servicios.map(([icon,title,text])=>`<article class="service"><div class="visual">${icon}</div><div><h3>${title}</h3><p>${text}</p><a class="text-link" href="#cotizacion">Solicitar información →</a></div></article>`).join('');
document.getElementById('priceRows').innerHTML='';
document.getElementById('newsGrid').innerHTML=CONFIG.noticias.map(n=>`<article><span class="source">${n[0]}</span><h3>${n[1]}</h3><p>${n[2]}</p><a class="text-link" target="_blank" rel="noopener" href="${n[3]}">Leer noticia ↗</a></article>`).join('');
const menuButton=document.querySelector('.menu-toggle'),nav=document.querySelector('nav');menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
const windowContent={responsable:['Gestión responsable','Le ayudamos a gestionar residuos con trazabilidad, valorización y compromiso ambiental.'],flota:['Flota operativa','Nuestras unidades están preparadas para realizar recolección y transporte seguro para su operación.'],seguridad:['Operaciones seguras','Personal capacitado, uso de EPP y controles de seguridad en cada etapa del servicio.']};const topPopover=document.querySelector('.top-popover');document.querySelectorAll('.window-trigger').forEach(button=>button.addEventListener('click',()=>{const item=windowContent[button.dataset.window];topPopover.querySelector('strong').textContent=item[0];topPopover.querySelector('p').textContent=item[1];topPopover.classList.add('open')}));topPopover.querySelector('.close-top').addEventListener('click',()=>topPopover.classList.remove('open'));
const popup=document.querySelector('.commercial-popup'),offers=[['¿Necesita recolección de residuos?','Solicitar cotización','#cotizacion'],['¿Quiere conocer nuestros precios?','Consultar precios','#precios'],['¿Necesita realizar trámites ambientales?','Consultar trámites','#tramites']];let offer=0;setInterval(()=>{if(!popup.classList.contains('hidden')){offer=(offer+1)%offers.length;document.getElementById('popupTitle').textContent=offers[offer][0];const l=document.getElementById('popupLink');l.textContent=offers[offer][1];l.href=offers[offer][2]}},6500);popup.querySelector('button').addEventListener('click',()=>popup.classList.add('hidden'));
const dialog=document.querySelector('.lightbox');document.querySelectorAll('.gallery button').forEach(b=>b.addEventListener('click',()=>{dialog.querySelector('img').src=b.dataset.image;dialog.showModal()}));dialog.querySelector('button').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
document.getElementById('quoteForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const t=`Hola ${CONFIG.empresa}, deseo solicitar una cotización.%0A%0ARUC: ${d.ruc}%0ANombre: ${d.nombre}%0ADistrito: ${d.distrito}%0AProvincia: ${d.provincia}%0AResiduo: ${d.residuo}%0ACantidad: ${d.cantidad}%0AServicio: ${d.servicio}%0AMensaje: ${d.mensaje}`;e.currentTarget.querySelector('.form-success').innerHTML=`Su consulta está lista para ser enviada a NAVISUA. <a href="https://wa.me/51${CONFIG.telefono}?text=${t}" target="_blank">Continuar por WhatsApp</a>`});
const links=[...document.querySelectorAll('nav a')];const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-45% 0px -45% 0px'});links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean).forEach(s=>observer.observe(s));

/* Conexión de precios: pegue aquí la URL CSV publicada desde Google Sheets. */
const GOOGLE_SHEETS_CSV_URL='https://docs.google.com/spreadsheets/d/e/2PACX-1vTI8Oe7LapcKTITokKrdK_hui-k5ArvJuipmOA9Rg3su90BL85mGUJlZWuyp9eC7xJs-B8wxIiVLeP-/pub?gid=195509324&single=true&output=csv';
const UTILIDAD_NAVISUA=.10;
const cleanText=value=>String(value||'').replace(/[<>&"']/g,char=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#039;'}[char]));
const csvCells=line=>{const cells=[];let value='',quoted=false;for(const char of line){if(char==='"')quoted=!quoted;else if(char===','&&!quoted){cells.push(value.trim());value=''}else value+=char}cells.push(value.trim());return cells};const csvToRows=csv=>{const lines=csv.trim().split(/\r?\n/);const headers=csvCells(lines.shift()).map(item=>item.toLowerCase());return lines.map(line=>{const cells=csvCells(line);return Object.fromEntries(headers.map((header,index)=>[header,cells[index]||'']))})};
const parsePrice=value=>Number(String(value).replace(/[^0-9.,-]/g,'').replace(',','.'));
const MATERIALES_NAVISUA=['Papel','Cartón','PET','Plástico duro','Film','Fierro','Aluminio','Cobre','Bronce','Otros'];
const mensajeMaterial=material=>{const mensajes={Papel:'Hola NAVISUA, deseo consultar disponibilidad y precio de Papel.',Cartón:'Hola NAVISUA, deseo consultar disponibilidad y precio de Cartón.',PET:'Hola NAVISUA, deseo consultar disponibilidad y precio de PET.','Plástico duro':'Hola NAVISUA, deseo consultar disponibilidad y precio de Plástico duro.',Film:'Hola NAVISUA, deseo consultar disponibilidad y precio de Film.',Fierro:'Hola NAVISUA, deseo consultar disponibilidad y precio de Fierro.',Aluminio:'Hola NAVISUA, deseo consultar disponibilidad y precio de Aluminio.',Cobre:'Hola NAVISUA, deseo consultar disponibilidad y precio de Cobre.',Bronce:'Hola NAVISUA, deseo consultar disponibilidad y precio de Bronce.',Otros:'Hola NAVISUA, deseo consultar disponibilidad y precio de otros residuos.'};return mensajes[material]||`Hola NAVISUA, deseo consultar disponibilidad y precio de ${material}.`};
const whatsappConsulta=material=>`https://wa.me/51${CONFIG.telefono}?text=${encodeURIComponent(mensajeMaterial(material))}`;
const formatDate=value=>{const parts=String(value||'').match(/(\d{1,2})\/(\d{1,2})\/(\d{4})/);return parts?`${parts[1].padStart(2,'0')}/${parts[2].padStart(2,'0')}/${parts[3]}`:''};
const renderUnavailable=materials=>{document.getElementById('priceRows').innerHTML=materials.map(material=>`<div class="price-row"><span>${cleanText(material)}</span><span>kg</span><span class="price-unavailable">Precio temporalmente no disponible. Consulte por WhatsApp.</span><a class="price-consult" target="_blank" rel="noopener" href="${whatsappConsulta(material)}">Consultar</a></div>`).join('')};
const renderPricesFromSheet=rows=>{const visibles=rows.filter(row=>String(row.estado||'activo').toLowerCase()!=='inactivo'&&row.material).slice(0,10);if(visibles.length!==10){renderUnavailable(MATERIALES_NAVISUA);return}document.getElementById('priceRows').innerHTML=visibles.map(row=>{const material=String(row.material).trim(),unidad=String(row.unidad||'kg').trim(),precio=parsePrice(row.precio_navisua),precioVisible=Number.isFinite(precio)&&precio>0?`S/ ${precio.toFixed(2)} por ${cleanText(unidad)}`:'Precio temporalmente no disponible. Consulte por WhatsApp.';return `<div class="price-row"><span>${cleanText(material)}</span><span>${cleanText(unidad)}</span><span class="price-sale">${precioVisible}</span><a class="price-consult" target="_blank" rel="noopener" href="${whatsappConsulta(material)}">Consultar</a></div>`}).join('');const fecha=formatDate(visibles.map(row=>row.actualizado).find(Boolean));document.querySelector('.price-table small').textContent=`Última actualización: ${fecha||'Precio temporalmente no disponible. Consulte por WhatsApp.'} · Precios de venta referenciales de NAVISUA. Sujetos a disponibilidad, volumen, calidad del material y condiciones comerciales. Consulte stock y precio final por WhatsApp.`};
renderUnavailable(MATERIALES_NAVISUA);
fetch(GOOGLE_SHEETS_CSV_URL).then(response=>{if(!response.ok)throw new Error('No fue posible leer la hoja');return response.text()}).then(csv=>renderPricesFromSheet(csvToRows(csv))).catch(()=>renderUnavailable(MATERIALES_NAVISUA));
