/* Configuración centralizada: actualice estos datos sin modificar el resto de la página. */
const CONFIG={empresa:'NAVISUA J&J E.I.R.L.',telefono:'947185874',correo:'navisua.eirl@gmail.com',precios:[['Papel','kg','Consultar'],['Cartón','kg','Consultar'],['PET','kg','Consultar'],['Plásticos','kg','Consultar'],['Film','kg','Consultar'],['Metales','kg','Consultar'],['Otros','kg','Consultar']],servicios:[['♻️','Recolección de residuos','Recojo programado y responsable para su operación.'],['🚛','Transporte de residuos sólidos','Traslado seguro con unidades operativas.'],['▤','Gestión de papel','Aprovechamiento y manejo de papel recuperable.'],['▣','Gestión de cartón','Segregación y valorización de cartón.'],['♳','Gestión de plásticos','Soluciones para plásticos y materiales recuperables.'],['⚙','Gestión de metales','Manejo de metales para valorización.'],['🌱','Materiales reciclables','Clasificación de materiales con potencial de recuperación.'],['↻','Valorización','Convertimos residuos en oportunidades de valor.'],['🏭','Servicios industriales','Atención para empresas e industrias.']],noticias:[['MINAM','Gestión integral de residuos sólidos','Información y recursos ambientales para la gestión responsable de residuos.','https://www.gob.pe/minam'],['OEFA','Fiscalización ambiental','Conozca las acciones y herramientas de fiscalización ambiental en Perú.','https://www.gob.pe/oefa'],['SINIA','Información ambiental','Acceda a datos y contenidos sobre ambiente, reciclaje y economía circular.','https://sinia.minam.gob.pe/']]};
const message=`Hola ${CONFIG.empresa}, deseo información sobre sus servicios de gestión de residuos sólidos.`;
document.querySelectorAll('[data-wa]').forEach(link=>link.href=`https://wa.me/51${CONFIG.telefono}?text=${encodeURIComponent(message)}`);
document.getElementById('serviceGrid').innerHTML=CONFIG.servicios.map(([icon,title,text])=>`<article class="service"><div class="visual">${icon}</div><div><h3>${title}</h3><p>${text}</p><a class="text-link" href="#cotizacion">Solicitar información →</a></div></article>`).join('');
document.getElementById('priceRows').innerHTML=CONFIG.precios.map(p=>`<div class="price-row"><span>${p[0]}</span><span>${p[1]}</span><strong>${p[2]}</strong></div>`).join('');
document.getElementById('newsGrid').innerHTML=CONFIG.noticias.map(n=>`<article><span class="source">${n[0]}</span><h3>${n[1]}</h3><p>${n[2]}</p><a class="text-link" target="_blank" rel="noopener" href="${n[3]}">Leer noticia ↗</a></article>`).join('');
const menuButton=document.querySelector('.menu-toggle'),nav=document.querySelector('nav');menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
const popup=document.querySelector('.commercial-popup'),offers=[['¿Necesita recolección de residuos?','Solicitar cotización','#cotizacion'],['¿Quiere conocer nuestros precios?','Consultar precios','#precios'],['¿Necesita realizar trámites ambientales?','Consultar trámites','#tramites']];let offer=0;setInterval(()=>{if(!popup.classList.contains('hidden')){offer=(offer+1)%offers.length;document.getElementById('popupTitle').textContent=offers[offer][0];const l=document.getElementById('popupLink');l.textContent=offers[offer][1];l.href=offers[offer][2]}},6500);popup.querySelector('button').addEventListener('click',()=>popup.classList.add('hidden'));
const dialog=document.querySelector('.lightbox');document.querySelectorAll('.gallery button').forEach(b=>b.addEventListener('click',()=>{dialog.querySelector('img').src=b.dataset.image;dialog.showModal()}));dialog.querySelector('button').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
document.getElementById('quoteForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const t=`Hola ${CONFIG.empresa}, deseo solicitar una cotización.%0A%0AEmpresa: ${d.empresa}%0ARUC: ${d.ruc}%0ANombre: ${d.nombre}%0ACelular: ${d.celular}%0ACorreo: ${d.correo}%0ADistrito: ${d.distrito}%0AProvincia: ${d.provincia}%0AResiduo: ${d.residuo}%0ACantidad: ${d.cantidad}%0AServicio: ${d.servicio}%0AMensaje: ${d.mensaje}`;e.currentTarget.querySelector('.form-success').innerHTML=`Su consulta está lista para ser enviada a NAVISUA. <a href="https://wa.me/51${CONFIG.telefono}?text=${t}" target="_blank">Continuar por WhatsApp</a>`});
const links=[...document.querySelectorAll('nav a')];const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-45% 0px -45% 0px'});links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean).forEach(s=>observer.observe(s));
